name       : perl-digest-hmac
version    : 1.03
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-HMAC-1.03.tar.gz : 3bc72c6d3ff144d73aefb90e9a78d33612d58cf1cd1631ecfb8985ba96da4a59
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Digest::HMAC - Keyed-Hashing for Message Authentication
description: |
    HMAC is used for message integrity checks between two parties that share a secret key, and works in combination with some other Digest algorithm, usually MD5 or SHA-1.  The HMAC mechanism is described in RFC 2104.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
